/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as defiV4Sol from "./DefiV4.sol";
export type { defiV4Sol };
import type * as defiV5Sol from "./DefiV5.sol";
export type { defiV5Sol };
import type * as defiPaperSol from "./Defi_paper.sol";
export type { defiPaperSol };
import type * as futuresLinkSol from "./FuturesLink.sol";
export type { futuresLinkSol };
import type * as futuresRegisterSol from "./FuturesRegister.sol";
export type { futuresRegisterSol };
import type * as futuresTokenSol from "./FuturesToken.sol";
export type { futuresTokenSol };
import type * as linkSol from "./Link.sol";
export type { linkSol };
import type * as linkV2Sol from "./LinkV2.sol";
export type { linkV2Sol };
import type * as maliciousSol from "./Malicious.sol";
export type { maliciousSol };
export type { BandwidthMarket } from "./BandwidthMarket";
export type { BandwidthNFT } from "./BandwidthNFT";
export type { BandwidthToken } from "./BandwidthToken";
export type { Defi } from "./Defi";
export type { DefiV1 } from "./DefiV1";
export type { DefiV2 } from "./DefiV2";
export type { DefiV3 } from "./DefiV3";
export type { Lock } from "./Lock";
